default: &default
  adapter: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: shop_development
  username: postgres
  password: Miwa7355608
  host: localhost
  port: 5432
  pool: 5


  test: 
    <<: *default
    database: shop_test

  production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
